// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e9c9478b-9045-4cab-99f4-7b6f153506ce",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_a9XwlGW0y",
    "aws_user_pools_web_client_id": "54art9hl17n2a6v9a4jac67qc2"
};


export default awsmobile;
